# Generated by Django 5.1.2 on 2024-12-22 04:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_remove_book_division_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="year",
        ),
    ]
