# Generated by Django 5.1.2 on 2024-12-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_remove_book_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("url_prefix", models.URLField()),
                ("url_suffix", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["state", "name"],
            },
        ),
    ]
