# Generated by Django 5.1.2 on 2024-12-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_library"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
