# Generated by Django 5.1.2 on 2024-12-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_book_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="library",
            name="state",
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name="LocalBookstore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("state", models.CharField(max_length=20)),
                ("zip_code", models.CharField(max_length=10)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("url_prefix", models.URLField(blank=True)),
                ("url_suffix", models.CharField(blank=True, max_length=200)),
                (
                    "web_platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.webplatform",
                    ),
                ),
            ],
            options={
                "ordering": ["state", "name"],
            },
        ),
        migrations.AddField(
            model_name="library",
            name="web_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.webplatform",
            ),
        ),
    ]
