# Generated by Django 5.1.2 on 2024-12-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_awardyearlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="bibliocommons_id",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
