# Generated by Django 5.1.2 on 2024-12-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_library_bibliocommons_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="asin",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
