# Generated by Django 5.1.2 on 2024-12-27 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_book_asin"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="book_images/"),
        ),
    ]
