# Generated by Django 5.1.2 on 2024-12-27 05:04

from django.db import migrations, models

import pages.models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=pages.models.upload_to_book_images
            ),
        ),
    ]
