# Generated by Django 5.1.2 on 2025-01-05 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="author",
            unique_together=set(),
        ),
    ]
