# Generated by Django 5.1.2 on 2025-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_alter_book_page_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="new_books_release_day_of_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
