# Generated by Django 5.1.2 on 2025-02-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0019_illustrator_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="book",
            name="illustrator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="pages.illustrator",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="pages_book_title_075451_idx"),
        ),
    ]
