# Generated by Django 5.1.2 on 2025-08-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0020_alter_book_options_alter_book_illustrator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="library",
            name="bibliocommons_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=256, unique=True),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["first_name"], name="pages_autho_first_n_81c774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["last_name"], name="pages_autho_last_na_51eb23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="pages_autho_first_n_83c76b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="illustrator",
            index=models.Index(
                fields=["first_name"], name="pages_illus_first_n_07bdc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="illustrator",
            index=models.Index(
                fields=["last_name"], name="pages_illus_last_na_486b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="illustrator",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="pages_illus_first_n_5e24ec_idx",
            ),
        ),
    ]
